# Generated by Django 2.2.1 on 2019-05-19 17:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='The CNPJ must have 14 numbers and the follow format: 99.999.999/9999-99', regex='[0-9]{2}\\.[0-9]{3}\\.[0-9]{3}\\/[0-9]{4}\\-[0-9]{2}')])),
                ('cnpj', models.CharField(max_length=18, validators=[django.core.validators.RegexValidator(message='The CNPJ must have 14 numbers and the follow format: 99.999.999/9999-99', regex='[0-9]{2}\\.[0-9]{3}\\.[0-9]{3}\\/[0-9]{4}\\-[0-9]{2}')], verbose_name='CNPJ')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20, verbose_name='Series')),
                ('number', models.IntegerField(default=0, verbose_name='Number')),
                ('name_description', models.TextField(blank=True, verbose_name='Name/Description')),
                ('weight', models.FloatField(default=0, verbose_name='Weight')),
                ('weight_metric', models.TextField(blank=True, default='Kg', verbose_name='Weight Metric')),
                ('volume', models.FloatField(default=0, verbose_name='Volume')),
                ('volume_metric', models.TextField(blank=True, default='m3', verbose_name='Volume Metric')),
                ('date', models.DateField(verbose_name='Date')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['id'],
            },
        ),
    ]
