# Generated by Django 2.2.1 on 2019-05-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalnote',
            options={'ordering': ['id'], 'verbose_name': 'FiscalNote', 'verbose_name_plural': 'FiscalNotes'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='volume_metric',
            field=models.CharField(blank=True, default='m3', max_length=4, verbose_name='Volume Metric'),
        ),
        migrations.AlterField(
            model_name='fiscalnote',
            name='weight_metric',
            field=models.CharField(blank=True, default='Kg', max_length=4, verbose_name='Weight Metric'),
        ),
    ]
