# Generated by Django 2.2.1 on 2019-05-19 19:24

from django.db import migrations, models
import register.validators


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190519_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[register.validators.cnpj_validator], verbose_name='CNPJ'),
        ),
    ]
